spring.application.name=WWW_T9
# [Ch??ng 6] C?u hình k?t n?i MariaDB
# ?? bài yêu c?u tên DB là QUANLYDIENTHOAI [cite: 2375]
spring.datasource.url=jdbc:mariadb://localhost:3306/QUANLYDIENTHOAIW9?useUnicode=true&characterEncoding=UTF-8
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

# [Ch??ng 6] Spring Data JPA t? ??ng t?o/c?p nh?t b?ng d?a trên @Entity
spring.jpa.hibernate.ddl-auto=update

# [Ch??ng 6] Hi?n th? câu SQL mà Spring Data t? t?o (?? debug)
spring.jpa.show-sql=true

# C?u hình cho phép upload file
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB